### ISSUE TITLE
Option for disable registering meta tags from widget

### ISSUE THREAD

**Issue by sokolnikov911** [yiimaker/yii2-social-share#12]
If I setted up all needed meta tags manually in view file, so I don't need to widget generated tags. So I should have some option for disabling meta tags which generated by widget drivers.

**Comment by greeflas** [comment]
@sokolnikov911 Good thing! I will implement it.

**Comment by greeflas** [comment]
@sokolnikov911 I implemented this future. Please check [configuration options](https://github.com/yiimaker/yii2-social-share/blob/master/docs/guide/configurator.md#configuration-options) of configurator. It available in 2.1.x-dev right now.

**Comment by sokolnikov911** [comment]
Seems to be everything OK. Thanks a lot.

**Comment by greeflas** [comment]
@sokolnikov911 Thank you!
