### ISSUE TITLE
Configurator: 'enableIcons' & 'enableDefaultAsset' instead 'enableDefaultIcons'

### ISSUE THREAD

**Issue by dimmitri** [yiimaker/yii2-social-share#16]
Many use a set of icons from other developers (Font Awesome). 
If you enable the setting 'enableDefaultIcons', the page loaded styles for your icons (SocialIconsAsset).

```php

'icons' => [
     \ymaker\social\share\drivers\Facebook::class => 'fab fa-facebook',
     \ymaker\social\share\drivers\GooglePlus::class => 'fab fa-google-plus-g',
 ],
```

 'enableIcons' - display icons instead of text.
 'enableDefaultAsset' - use your icon styles.

**Comment by greeflas** [comment]
@dimmitri Good suggestion, it will be implemented. Thank you!
