### ISSUE TITLE
Failed to instantiate component or class "socialShare".

### ISSUE THREAD

**Issue by ilhamsr** [yiimaker/yii2-social-share#18]
i'm pretty new with yii2, i've added a widget like this
 `<?= \ymaker\social\share\widgets\SocialShare::widget([
                  'configurator'  => 'socialShare',
                  'url'           => \yii\helpers\Url::to('http://facebook.com', true),
                  'title'         => 'FB',
                  'description'   => 'Description of the page...',
              ]); ?>` 
to my view, but it shows me 
_Invalid Configuration – yii\base\InvalidConfigException
Failed to instantiate component or class "socialShare"_ 
error, should i use the 'use' statement at the start of my file ?

**Comment by greeflas** [comment]
Hey @ilhamsr ! I think you just need to configure "social network configurator". Here is a [documentation](https://github.com/yiimaker/yii2-social-share/blob/master/docs/guide/installation.md#configuring-application) with example.

**Comment by ilhamsr** [comment]
okay, its fixed already 👍 thx
