### ISSUE TITLE
Need separate meta tag for index page when this plugin is installed

### ISSUE THREAD

**Issue by shaileshe2logy** [yiimaker/yii2-social-share#19]
We are using this plugin in our below website to share individual deal share on facebook. When we are using below website index page url in facebook ads for promotion( or in facebook debugger) then its taking any random deal as post.
https://www.flashmarket.com.au/

How we can define meta tag for index page website url?

**Comment by greeflas** [comment]
Hi @shaileshe2logy ! I see that you are using this social-share widget for each post on your index page. In this case you should disable registration of meta tags in configurator's settings: https://github.com/yiimaker/yii2-social-share/blob/master/docs/guide/configurator.md

```php
// ...
'socialShare' => [
    'class' => \ymaker\social\share\configurators\Configurator::class,
    'registerMetaTags' => false,
    // ...
],
```
