### ISSUE TITLE
Setting unknown property: ymaker\social\share\widgets\SocialShare::configuratorId

### ISSUE THREAD

**Issue by julianyraiol** [yiimaker/yii2-social-share#9]
Hello!

How can I use the configuratorId? I configured the Socialnetwork with facebook and when I used the widget in my website show this message: 
"Setting unknown property:  ymaker\social\share\widgets\SocialShare::configuratorId"

**Comment by sokolnikov911** [comment]
If you use dev-master version, depends on commit https://github.com/yiimaker/yii2-social-share/commit/abf44fc84900c327859a59501cfe88f4f0140fb0 you should use `configurator` attribute instead of `configuratorId`.

**Comment by julianyraiol** [comment]
thanks, @sokolnikov911
